name: "Abhishek Kumar"
url: "https://abkumar.me"

#gems:
#- jekyll-sitemap

markdown: kramdown

# kramdown:
  # input: GFM
  # syntax_highlighter: rouge

highlighter: pygments

permalink: /blog/:year/:month/:title/
