name: "Abhishek Kumar"
url: "https://abkumar.me"

defaults:
  - scope:
      path: "_posts/posts"
    values:
      type: "posts"

#gems:
#- jekyll-sitemap
destination: public
# Build settings
markdown: kramdown
kramdown:
  math_engine: mathjax
highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

permalink: pretty
permalink: /:year/:title/
