name: "Abhishek Kumar"
url: "https://abkumar.me"

#gems:
#- jekyll-sitemap
destination: public
# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

permalink: pretty
permalink: /:year/:title/
